volumes:
  ghost:
  ghost-db:
  traefik:

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:

  traefik:
    restart: unless-stopped
    container_name: traefik
    image: traefik:3.0
    ports:
      - '80:80'
      - '443:443'
      - '81:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - traefik:/letsencrypt
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.ajtech.nl`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls.certresolver=cloudflare'
    command:
      - '--api=true'
      - '--providers.docker'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --providers.docker.network=docker
      - --providers.docker.exposedByDefault=false
      - '--providers.docker.defaultRule=Host(`{{ normalize .Name }}.ajtech.nl`)'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.cloudflare.acme.email=${CF_EMAIL}'
      - '--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json'
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - proxy_net 

  ghost:
    image: ghost:5
    container_name: ghost
    restart: unless-stopped
    networks:
      - proxy_net
    ports:
      - "2368:2368"
    depends_on:
      - ghost_db
      - traefik
    environment:
      url: https://ajtech.nl
      NODE_ENV: production
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ghostdb
      mail__from: "blog@ajtech.nl"
      mail__transport: "SMTP"
      mail__options__host: "${MAIL_HOST}"
      mail__options__port: "${MAIL_PORT}"
      mail__options__auth__user: "${MAIL_USER}"
      mail__options__auth__pass: "${MAIL_PASSWORD}"
    volumes:
      - ghost:/var/lib/ghost/content
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.entrypoints=websecure
      - 'traefik.http.routers.ghost.tls.certresolver=cloudflare'
      - 'traefik.http.routers.ghost.rule=Host(`ajtech.nl`)'
      - 'traefik.http.services.ghost.loadbalancer.server.port=2368'

  ghost_db:
    image: mysql:8.1
    container_name: ghost_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - proxy_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ghostdb
    volumes:
      - ghost-db:/var/lib/mysql
